services:
  postgres-orders:
    image: postgres:15-alpine
    container_name: bakery-orders-db
    restart: unless-stopped
    ports:
      - "5434:5432"  # Different port to avoid conflicts
    environment:
      POSTGRES_DB: bakery_orders
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - bakery-network

volumes:
  postgres_orders_data:
    driver: local

networks:
  bakery-network:
    driver: bridge
