# Server Configuration
server:
  port: 8084

# Spring Application Configuration
spring:
  application:
    name: order-service
  docker:
    compose:
      file: docker-compose-orders-db.yml
      enabled: false

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5434/bakery_orders
    username: order_user
    password: order_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Jackson Configuration
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Feign Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# Management & Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

# Order Service Specific Configuration
order:
  delivery:
    default-time-minutes: 60
    max-time-minutes: 180
  limits:
    max-items-per-order: 50
    max-order-value: 500.00
  tax:
    rate: 0.08 # 8% tax rate
  discount:
    max-percentage: 30

# External Service URLs (for WebClient)
external-services:
  auth-service:
    base-url: http://localhost:8082
  product-service:
    base-url: http://localhost:8083

# Logging Configuration
logging:
  level:
    com.shah_s.bakery_order_service: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    feign: DEBUG
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/order-service.log
    max-size: 10MB
    max-history: 30
